//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MajorSilenceConnect.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MajorSilenceConnect.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] cad {
            get {
                object obj = ResourceManager.GetObject("cad", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;NewDataSet&gt;
        ///
        ///  &lt;helpdesk&gt;
        ///    &lt;support&gt;Support 1&lt;/support&gt;
        ///    &lt;address&gt;majorsilence.no-ip.org:5500&lt;/address&gt;
        ///  &lt;/helpdesk&gt;
        ///
        ///&lt;/NewDataSet&gt;.
        /// </summary>
        internal static string helpdesk {
            get {
                return ResourceManager.GetString("helpdesk", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon majorsilence {
            get {
                object obj = ResourceManager.GetObject("majorsilence", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static byte[] MSRC4Plugin {
            get {
                object obj = ResourceManager.GetObject("MSRC4Plugin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SCHook {
            get {
                object obj = ResourceManager.GetObject("SCHook", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Permissions
        ///[admin]
        ///FileTransferEnabled = 1
        ///FTUserImpersonation = 1
        ///BlankMonitorEnabled = 1
        ///CaptureAlphaBlending = 0
        ///BlackAlphaBlending = 1
        ///DefaultScale = 1
        ///UseDSMPlugin = 0
        ///DSMPlugin = MSRC4Plugin.dsm
        ///primary = 1
        ///secondary = 0
        ///SocketConnect = 1
        ///HTTPConnect = 0
        ///AutoPortSelect = 1
        ///InputsEnabled = 1
        ///LocalInputsDisabled = 0
        ///IdleTimeout = 0
        ///EnableJapInput = 0
        ///QueryTimeout = 10
        ///QueryAccept = 0
        ///LockSetting = 0
        ///MaxCpu = 50
        ///RemoveWallpaper = 1
        ///RemoveAero = 1
        ///DebugMode = 0
        ///Avilog = 0
        ///path [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ultravnc {
            get {
                return ResourceManager.GetString("ultravnc", resourceCulture);
            }
        }
        
        internal static byte[] vnchooks {
            get {
                object obj = ResourceManager.GetObject("vnchooks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] winvnc {
            get {
                object obj = ResourceManager.GetObject("winvnc", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
